done module 2-1
js-tasks-ru/jsbasic-20220211_evgeniy-gusev7 pull request #3
Opened 2022-02-17 09:04 UTC by GusevE

2022-02-17 09:05 UTC, jsru commented
Добавляю преподавателя (@SinimaWath) для код-ревью.

2022-02-17 10:56 UTC, jsru commented
Решение было обновлено, посмотрим что скажет @SinimaWath

2022-02-17 11:58 UTC, jsru commented
Решение было обновлено, посмотрим что скажет @SinimaWath

2022-02-18 09:46 UTC, SinimaWath requested changes

2022-02-18 09:46 UTC, SinimaWath commented on 2-module/3-task/task.test.js
> +  // });
Верни ) И давай решать задачу. Не нужно комментировать тесты

2022-02-18 13:27 UTC, jsru commented
Добавляю преподавателя (@SinimaWath) для код-ревью.

2022-02-18 19:15 UTC, SinimaWath approved these changes

2022-02-18 19:15 UTC, merged